# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "svn2git"
  s.version = "2.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Coglan", "Kevin Menard"]
  s.date = "2012-11-20"
  s.email = "nirvdrum@gmail.com"
  s.executables = ["svn2git"]
  s.extra_rdoc_files = [
    "ChangeLog.markdown",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "ChangeLog.markdown",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "bin/svn2git",
     "lib/svn2git.rb",
     "lib/svn2git/blah.rb",
     "lib/svn2git/migration.rb",
     "svn2git.gemspec"
  ]
  s.homepage = "https://www.negativetwenty.net/redmine/projects/svn2git"
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "A tool for migrating svn projects to git"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
